apiVersion: v1
kind: Service
metadata:
  name: posts-linux-service
  labels:
    app: posts-microservice
spec:
  type: LoadBalancer
  selector:
    app: posts-microservice
  ports:
    - port: 8002
      targetPort: 8002